name: Check
runs-on: ubuntu-latest
steps:
  - uses: Marcisbee/dependency-check-action
    with:
      PATH: "/projects/server"
      IGNORE_PACKAGES:
        - @babel/core
      IGNORE_FILES:
        - .test.js
        - /customfile.js